Made script more robust, and parameterized it.

diff --git a/models/generic-amd64-pc/start_encrypted_disks_and_dependent_services b/models/generic-amd64-pc/start_encrypted_disks_and_dependent_services
--- a/models/generic-amd64-pc/start_encrypted_disks_and_dependent_services
+++ b/models/generic-amd64-pc/start_encrypted_disks_and_dependent_services
@@ -1,22 +1,52 @@
 #! /bin/bash
 
-# This script starts the encrypted disks, mounts any subvolumes, and then
-# starts the services that depend on those encrypted disks.
+# This script starts the encrypted disks, mounts any mounts in /etc/fstab
+# that have the noauto option, and then starts the services passed on the
+# commandline.
 
-cryptdisks_start enc1
-cryptdisks_start enc2
-cryptdisks_start enc3
-cryptdisks_start enc4
+if [ "$#" == "0" ] then
+    echo "No services given; taking no action."
+    exit 1
+fi
 
-mount /mnt/media
-mount /var/spool/burp
+for i in $(grep ^enc /etc/crypttab | cut -f 1 -d ' '); do
+    cryptsetup status enc1 | head -1 | grep -qs active
+    if [ $? == 0 ] then
+        echo "${i} is already active, skipping."
+    else
+        cryptdisks_start ${i}
+        if [ $? == 1 ] then
+            >&2 echo "Failed to open encrypted device ${i}. Aborting." 
+            exit 1
+        fi
+    fi
+done
 
-systemctl start subsonic
-sleep 2
-#systemctl status subsonic
+for i in $(grep -v '^#' /etc/fstab | grep noauto | cut -f 2 -d ' '); do
+    echo "Mounting ${i}"
+    mount ${i}
+    if [ $? == 1 ] then
+        >&2 echo "Failed to mount ${i}. Aborting"
+        exit 1
+    fi
+done
 
-systemctl start burp
-sleep 2
-#systemctl status burp
+while (( "$#" )); do
+    if [ $(systemctl is-active ${1}) == "active") ] then
+        systemctl status ${1} | grep -qs 'active\s*(running)'
+        if [ $? == 0 ] then
+            echo "${1} is already running, skipping"
+        else
+            echo "Starting ${1}"
+            systemctl start ${1}
+        fi
+    else
+        >&2 echo "Service ${1} is not active, skipping."
+    fi
+
+    sleep 2
+
+    shift
+done
 
 # vim:tw=76:sts=4:sw=4
