bringing cryptdisk stuff up to date

diff --git a/decrypt_keyctl.patch b/decrypt_keyctl.patch
--- a/decrypt_keyctl.patch
+++ b/decrypt_keyctl.patch
@@ -1,28 +1,79 @@
---- decrypt_keyctl.orig	2016-12-18 07:20:33.412163916 -0500
-+++ decrypt_keyctl	2016-12-18 07:22:06.024161012 -0500
-@@ -31,7 +31,7 @@
- test -x "$STTY_" && PW_READER_='stty'           # 1. backup method
- test -x "$ASKPASS_" && PW_READER_='askpass'     # prefered method
- 
--KID_=$(keyctl search @u user "$ID_" 2>/dev/null)
-+KID_=$(keyctl search @s user "$ID_" 2>/dev/null)
- if [ $? -ne 0 ] || [ -z "$KID_" ] || [ "$CRYPTTAB_TRIED" -gt 0 ]; then
-     # key not found or wrong, ask the user
-     case "$PW_READER_" in
-@@ -70,13 +70,13 @@
-         # I have cached wrong password and now i may use either `keyctl update`
-         # to update $KID_ or just unlink old key, and add new. With `update` i
-         # may hit "Key has expired", though. So i'll go "unlink and add" way.
--        keyctl unlink $KID_ @u
-+        keyctl unlink $KID_ @s
-         KID_=""
-     fi
--    KID_=$(echo -n "$KEY_" |keyctl padd user "$ID_" @u)
-+    KID_=$(echo -n "$KEY_" |keyctl padd user "$ID_" @s)
-     [ -z "$KID_" ] && die "Error adding passphrase to kernel keyring"
-     if ! keyctl timeout $KID_ $TIMEOUT_; then
--        keyctl unlink $KID_ @u
-+        keyctl unlink $KID_ @s
-         die "Error setting timeout on key ($KID_), removing"
-     fi
- else
+*** decrypt_keyctl.orig	2018-04-13 05:10:47.322786192 -0400
+--- decrypt_keyctl	2018-04-13 04:56:08.593941949 -0400
+***************
+*** 13,18 ****
+--- 13,38 ----
+  #  test1 and test2 have the same identifier thus test2 does not need a password
+  #  typed in manually
+  
++ 
++ if [ -z $RECURSE_COUNTER ]; then
++     RECURSE_COUNTER=0
++ fi
++ 
++ RECURSE_COUNTER=$(( $RECURSE_COUNTER + 1 ))
++ 
++ if [ $RECURSE_COUNTER -eq 1 ]; then
++     export RECURSE_COUNTER
++     # Start a new program with a new session keyring. This guarantees that
++     # there _is_ a session keyring to use below.  There is an edge case
++     # where the session keyring has expired (typically after three days)
++     # and creating a new session keyring avoids that pitfall.  Here we're
++     # calling ourselves... the test on RECURSE_COUNTER makes sure the
++     # child process doesn't also recurse but instead executes the body
++     # of the script below.
++     keyctl session - $0 $1
++     exit $?
++ fi
++ 
+  die()
+  {
+      echo "$@" >&2
+***************
+*** 73,80 ****
+          keyctl unlink $KID_ @u
+          KID_=""
+      fi
+!     KID_=$(echo -n "$KEY_" |keyctl padd user "$ID_" @u)
+      [ -z "$KID_" ] && die "Error adding passphrase to kernel keyring"
+      if ! keyctl timeout $KID_ $TIMEOUT_; then
+          keyctl unlink $KID_ @u
+          die "Error setting timeout on key ($KID_), removing"
+--- 93,129 ----
+          keyctl unlink $KID_ @u
+          KID_=""
+      fi
+!     # Use the session keyring, not the user keyring, as we may not
+!     # possess the user keying.  This happens when you su to root from
+!     # an ssh session, and in that case we are the owner of the user
+!     # keyring, but not the possessor of it.  This doesn't seem to happen
+!     # when you su to root from the console.  I don't really understand
+!     # why there is a difference, but there is.
+!     KID_=$(echo -n "$KEY_" |keyctl padd user "$ID_" @s)
+      [ -z "$KID_" ] && die "Error adding passphrase to kernel keyring"
++ 
++     # Set the permissions on the new key (we possess it since we possess
++     # the session (@s) keyring, so we can set the permissions).
++     if ! keyctl setperm $KID_ 0x3f3f0000; then
++ 	keyctl unlink $KID_ @s
++ 	die "Error setting permissions on key ($KID_), removing..."
++     fi
++ 
++     # Now link the new key to the user (@u, in this case root's) keyring
++     # so that it persists across invocations of this script.
++     if ! keyctl link $KID_ @u; then
++ 	keyctl unlink $KID_ @s
++ 	die "Error linking key ($KID_) to the @u keyring, removing..."
++     fi
++ 
++     # Finally unlink the key from the session keyring (@s) so the original
++     # possessor of the key (could be anyone if they su root) doesn't have
++     # access to the key. Not sure this is really necessary, but good
++     # practice.
++     if ! keyctl unlink $KID_ @s; then
++ 	echo "WARNING: unable to unlink key ($KID_) from the @s keyring." >&2
++     fi
++ 
+      if ! keyctl timeout $KID_ $TIMEOUT_; then
+          keyctl unlink $KID_ @u
+          die "Error setting timeout on key ($KID_), removing"
